### ISSUE TITLE
Trealla does not print a newline / suffix continued construct

### ISSUE THREAD

**Issue by jacobfriedman** [jacobfriedman/vsc-logtalk#5]
**GProlog**
```
% [ /home/jacob/projects/logtalk3/examples/errors/errors_loader.lgt loaded ]
(14 ms) yes
| ?- 
```
**SWI**
```
% [ /home/jacob/projects/logtalk3/examples/errors/errors_loader.lgt loaded ]
true.
?- 
```

**Trealla**
```
% [ /home/jacob/projects/logtalk3/examples/errors/errors_loader.lgt loaded ]
true 
```
... The suffix on Trealla does not print in the same manner as SWI or GProlog (prompt). I wonder if this is a Trealla version problem.

**Comment by jacobfriedman** [comment]
Note: this leads to awkward continuous script-calling & eventual shutdown.

**Comment by pmoura** [comment]
Trealla leaves a choice-point. Possibly a predicate indexing issue.
